/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI function prototypes
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#ifndef TEST_QMP_COMMANDS_H
#define TEST_QMP_COMMANDS_H

#include "test-qapi-types.h"
#include "error.h"

void qmp_user_def_cmd(Error **errp);
void qmp_user_def_cmd1(UserDefOne * ud1a, Error **errp);
UserDefTwo * qmp_user_def_cmd2(UserDefOne * ud1a, UserDefOne * ud1b, Error **errp);

#endif
